In [2]:
import numpy as np

## Datatypes and attributes

In [3]:
# Numpy's main datatype is ndarray

# 1-D array
al = np.array([1,2,3])
al

array([1, 2, 3])

In [4]:
type(al)

numpy.ndarray

In [5]:
# 2 - D array

a2 = np.array([[1 ,2 ,3 ],
               [4 , 5 ,6 ]])

# 3 - D array

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [6]:
a2 

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
al.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
al.ndim , a2.ndim , a3.ndim

(1, 2, 3)

In [12]:
al.dtype

dtype('int64')

In [13]:
al.size ,a2.size , a3.size

(3, 6, 18)

In [14]:
# Create a DataFrame from a numpy array

import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## Creating arrays

In [15]:
ones = np.ones((2 , 3)) 
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(0 ,10, 2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array = np.random.randint(0 ,10 , size = ( 3, 5))
random_array

array([[0, 6, 9, 7, 2],
       [1, 1, 4, 8, 3],
       [6, 1, 6, 8, 7]], dtype=int32)

In [19]:
random_array_2 = np.random.random((5,3))
random_array

array([[0, 6, 9, 7, 2],
       [1, 1, 4, 8, 3],
       [6, 1, 6, 8, 7]], dtype=int32)

In [20]:
np.random.seed(7)
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [21]:
np.unique(random_array)

array([0, 1, 2, 3, 4, 6, 7, 8, 9], dtype=int32)

In [22]:
al

array([1, 2, 3])

In [23]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
al[0]

np.int64(1)

In [26]:
a3[:2 ,:2 ,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## Manipulating and comparing arrays

### Arithmetic

In [27]:
al

array([1, 2, 3])

In [28]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [29]:
al + ones

array([2., 3., 4.])

In [30]:
al - ones

array([0., 1., 2.])

In [31]:
al * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [32]:
# floor division removes decimals
a2 // al


array([[1, 1, 1],
       [4, 2, 2]])

In [33]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

### Aggregation

 Aggregation  = performing the same operation on number of things

In [36]:
listy_list = [1,2,3]
type(listy_list)

list

In [37]:
sum(listy_list)

6

In [38]:
sum(al)

np.int64(6)

 Use python's methods (sum()) on python datatypes 
use numpy's methods on numpy arrays (np.sum())

In [40]:
massive_array  = np.random.random(100000)
massive_array

array([0.81524212, 0.66264752, 0.36896114, ..., 0.40812976, 0.53640774,
       0.74525681], shape=(100000,))

In [41]:
%timeit sum(massive_array)       # python sum
%timeit np.sum(massive_array)   # numpy np.sum

5.76 ms ± 267 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
29.5 μs ± 908 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [42]:
np.mean(a2)

np.float64(3.5)

In [43]:
np.max(a2)

np.int64(6)

In [44]:
np.min(a2)

np.int64(1)

In [45]:
np.std(a2)

np.float64(1.707825127659933)

In [46]:
np.var(a2)

np.float64(2.9166666666666665)

In [47]:
np.sqrt (np.var(a2))

np.float64(1.707825127659933)

### Reshaping and transposing 

In [49]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [51]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [52]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [53]:
# Trranspose
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Dot product

In [54]:
np.random.seed(0)

mat1 = np.random.randint(10 , size =(5,3))
mat2 = np.random.randint(10 , size =(5,3))

In [55]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [56]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [57]:
mat3  = np.dot(mat1 , mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

## Dot product example ( nut butter sales)

In [58]:
np.random.seed(0)

# no.of jars sold
sales_amounts = np.random.randint(20 ,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [60]:
# create weekly sales dataframe

weekly_sales = pd.DataFrame(sales_amounts ,
                            index =["Mon" ,"Tues" , "Wed" , "Thurs" , "Fri"],
                            columns =["Almond butter " , "Peanut butter" , "Cashew butter"])
weekly_sales              

Almond butter   Peanut butter  Cashew butter
Mon                12             15              0
Tues                3              3              7
Wed                 9             19             18
Thurs               4              6             12
Fri                 1              6              7

In [62]:
# Create prices array

prices = np.array ([10,8,12])
prices

array([10,  8, 12])

In [64]:
# butter_prices dataframe create
butter_prices = pd.DataFrame(prices.reshape(1,3) ,
                             index =["Price"],
                             columns = ["Almond butter " , "Peanut butter" , "Cashew butter"])
butter_prices

Almond butter   Peanut butter  Cashew butter
Price              10              8             12

In [66]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [67]:
# create daily sales

butter_prices.shape , weekly_sales.shape

((1, 3), (5, 3))

In [68]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [69]:
weekly_sales["Total($)" ] = daily_sales.T
weekly_sales

Almond butter   Peanut butter  Cashew butter  Total($)
Mon                12             15              0       240
Tues                3              3              7       138
Wed                 9             19             18       458
Thurs               4              6             12       232
Fri                 1              6              7       142

# Comparison Operators

In [70]:
al

array([1, 2, 3])

In [71]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
al > a2

array([[False, False, False],
       [False, False, False]])

# Sorting arrays

In [73]:
random_array = np.random.randint(10,size = (3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]], dtype=int32)

In [74]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]], dtype=int32)

In [75]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

# Image to numpy array

<img src = "images/panda.jpeg"/>

In [80]:
# turn image into numpy array

from matplotlib.image import imread
panda = imread("images/panda.jpeg")
print(type(panda))

<class 'numpy.ndarray'>


In [81]:
panda

array([[[14, 27, 17],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [41, 34, 24]],

       [[14, 27, 17],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [42, 35, 25]],

       [[13, 26, 16],
        [14, 27, 17],
        [12, 28, 17],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [42, 35, 25]],

       ...,

       [[47, 32, 27],
        [48, 33, 28],
        [48, 33, 26],
        ...,
        [ 6,  6,  8],
        [ 6,  6,  8],
        [ 6,  6,  8]],

       [[39, 24, 19],
        [40, 25, 18],
        [42, 27, 20],
        ...,
        [ 6,  6,  8],
        [ 6,  6,  8],
        [ 6,  6,  8]],

       [[32, 17, 10],
        [33, 18, 11],
        [36, 21, 14],
        ...,
        [ 6,  6,  8],
        [ 6,  6,  8],
        [ 6,  6,  8]]], shape=(852, 1280, 3), dtype=uint8)

<img src = "images/car-photo.png"/>

In [82]:
car = imread ("images/car-photo.png")

In [84]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]],
      shape=(1, 575, 4), dtype=float32)

<img src = "images/dog-photo.png"/>

In [87]:
dog = imread ("images/dog-photo.png")

In [88]:
dog[:2]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]]],
      shape=(2, 575, 4), dtype=float32)