## Checking whether the pytorch is installed or not 

In [5]:
import torch, torchvision, torchaudio
print(torch.__version__)
print(torchvision.__version__)
print(torchaudio.__version__)


2.5.1
0.20.1
2.5.1


## Converting list to tensor

In [6]:
heights = [189, 170, 189, 163, 183, 171, 185,168, 173, 183, 173, 173, 175, 178,
           183, 193, 178, 173, 174, 183, 183,180, 168, 180, 170, 178, 182, 180,
           183, 178, 182, 188, 175, 179, 183,193, 182, 183, 177, 185, 188, 188,
           182, 185, 191, 183]

In [8]:
heights_tensor = torch.tensor(heights , dtype = torch.float64)
print(heights_tensor)

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178., 183., 193., 178., 173., 174., 183., 183., 180., 168., 180.,
        170., 178., 182., 180., 183., 178., 182., 188., 175., 179., 183., 193.,
        182., 183., 177., 185., 188., 188., 182., 185., 191., 183.],
       dtype=torch.float64)


## Two ways of specifying tensor types

In [10]:
# Way 1 

t1 = torch.IntTensor([1,2,3])
print(t1)

tensor([1, 2, 3], dtype=torch.int32)


In [11]:
# way 2

t2 = torch.tensor([1,2,3], dtype = torch.int)
print(t2)

tensor([1, 2, 3], dtype=torch.int32)


In [17]:
# exercise 2.1

python_list = ([5,8,9])

t1 = torch.DoubleTensor(python_list)
print(t1)

t2 = torch.tensor(python_list , dtype = torch.float64)
print(t2)

tensor([5., 8., 9.], dtype=torch.float64)
tensor([5., 8., 9.], dtype=torch.float64)


## creating tensor with only 0 or 1

In [20]:
# 2-D

t1 = torch.zeros(2,3)
print(t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [21]:
# 3-D

t2 = torch.ones(1,4,5)
print(t2)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [22]:
# exercise 2.2

t3 = torch.zeros(2,3,4)
print(t3)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


## Numpy array into tensor

In [24]:
import numpy as np

nparr = np.array(range(10))
pt_tensor = torch.tensor(nparr , dtype = torch.int)
print(pt_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


## index pytorch tensor

In [27]:
# counting from front

height = heights_tensor[2]
print(height)

tensor(189., dtype=torch.float64)


In [29]:
# counting from back

height = heights_tensor[-2]
print(height)

tensor(191., dtype=torch.float64)


## slice pytorch tensor

In [34]:
# slicing from front

two_height = heights_tensor[:2]
print(two_height)

tensor([189., 170.], dtype=torch.float64)


In [35]:
# slicing from back

last_five_height = heights_tensor[-5:]
print(last_five_height)

tensor([188., 182., 185., 191., 183.], dtype=torch.float64)


In [36]:
# exercise 2.3

five_height = heights_tensor[:5]
print(five_height)

tensor([189., 170., 189., 163., 183.], dtype=torch.float64)


## pytorch tensor shapes

In [37]:
print(heights_tensor.shape)

torch.Size([46])


In [38]:
heights_in_feet = heights_tensor / 30.48
print(heights_in_feet)

tensor([6.2008, 5.5774, 6.2008, 5.3478, 6.0039, 5.6102, 6.0696, 5.5118, 5.6759,
        6.0039, 5.6759, 5.6759, 5.7415, 5.8399, 6.0039, 6.3320, 5.8399, 5.6759,
        5.7087, 6.0039, 6.0039, 5.9055, 5.5118, 5.9055, 5.5774, 5.8399, 5.9711,
        5.9055, 6.0039, 5.8399, 5.9711, 6.1680, 5.7415, 5.8727, 6.0039, 6.3320,
        5.9711, 6.0039, 5.8071, 6.0696, 6.1680, 6.1680, 5.9711, 6.0696, 6.2664,
        6.0039], dtype=torch.float64)


## concatenation of tensors

In [39]:
height_2 = torch.cat([heights_tensor , heights_in_feet] , dim = 0)
print(height_2)

tensor([189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
        168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
        183.0000, 193.0000, 178.0000, 173.0000, 174.0000, 183.0000, 183.0000,
        180.0000, 168.0000, 180.0000, 170.0000, 178.0000, 182.0000, 180.0000,
        183.0000, 178.0000, 182.0000, 188.0000, 175.0000, 179.0000, 183.0000,
        193.0000, 182.0000, 183.0000, 177.0000, 185.0000, 188.0000, 188.0000,
        182.0000, 185.0000, 191.0000, 183.0000,   6.2008,   5.5774,   6.2008,
          5.3478,   6.0039,   5.6102,   6.0696,   5.5118,   5.6759,   6.0039,
          5.6759,   5.6759,   5.7415,   5.8399,   6.0039,   6.3320,   5.8399,
          5.6759,   5.7087,   6.0039,   6.0039,   5.9055,   5.5118,   5.9055,
          5.5774,   5.8399,   5.9711,   5.9055,   6.0039,   5.8399,   5.9711,
          6.1680,   5.7415,   5.8727,   6.0039,   6.3320,   5.9711,   6.0039,
          5.8071,   6.0696,   6.1680,   6.1680,   5.9711,   6.06

In [42]:
heights_reshaped = height_2.reshape(2, 46)
print(heights_reshaped)

tensor([[189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
         168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
         183.0000, 193.0000, 178.0000, 173.0000, 174.0000, 183.0000, 183.0000,
         180.0000, 168.0000, 180.0000, 170.0000, 178.0000, 182.0000, 180.0000,
         183.0000, 178.0000, 182.0000, 188.0000, 175.0000, 179.0000, 183.0000,
         193.0000, 182.0000, 183.0000, 177.0000, 185.0000, 188.0000, 188.0000,
         182.0000, 185.0000, 191.0000, 183.0000],
        [  6.2008,   5.5774,   6.2008,   5.3478,   6.0039,   5.6102,   6.0696,
           5.5118,   5.6759,   6.0039,   5.6759,   5.6759,   5.7415,   5.8399,
           6.0039,   6.3320,   5.8399,   5.6759,   5.7087,   6.0039,   6.0039,
           5.9055,   5.5118,   5.9055,   5.5774,   5.8399,   5.9711,   5.9055,
           6.0039,   5.8399,   5.9711,   6.1680,   5.7415,   5.8727,   6.0039,
           6.3320,   5.9711,   6.0039,   5.8071,   6.0696,   6.1680,   6.1680,
  

In [43]:
print(heights_reshaped[1,-2])

tensor(6.2664, dtype=torch.float64)


In [44]:
# exercise 2.4

print(heights_reshaped[0,-3])

tensor(185., dtype=torch.float64)


## mathematical operations on pytorch tensors

In [46]:
print(torch.median(heights_reshaped))

tensor(6.3320, dtype=torch.float64)


In [47]:
values, indices = torch.max(heights_reshaped, dim=1)
print(values)
print(indices)

tensor([193.0000,   6.3320], dtype=torch.float64)
tensor([15, 15])


In [48]:
# exercise 2.5

values, indices = torch.min(heights_reshaped, dim=1)
print(values)
print(indices)

tensor([163.0000,   5.3478], dtype=torch.float64)
tensor([3, 3])
